#!/usr/bin/env bash
set -e

while [ $# -gt 0 ]; do
    user=$1
    name=$(echo ${user} | tr ' ' '-')
    git log --name-only --pretty=format: --author "${user}" | sed -e 's:[[:blank:]]*::g' | sort -u > ${name}.files
    git ls-files | sed -e 's:[[:blank:]]*::g' | sort -u > git.files

    comm -12 ${name}.files git.files > ${name}.head.changed
    comm -23 ${name}.files git.files > ${name}.head.deleted
    comm -13 ${name}.files git.files > ${name}.head.intact

    echo "${user} changed $(cat ${name}.head.changed | wc -l) files , deleted $(cat ${name}.head.deleted | wc -l) files, never edited $(cat ${name}.head.intact | wc -l) files"
    shift
done
